name: CI

on: pull_request

jobs:

  ktLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: KtLint Check
        run: ./gradlew ktlintCheck


  unit_tests:
    needs: [ktLint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Unit tests
        run: ./gradlew test


  android_tests:
    needs: [unit_tests]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace


  build_and_assemble:
    needs: [android_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Project
        run: ./gradlew build

      - name: Aseemble
        run: ./gradlew assemble